default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mind_app_development

test:
  <<: *default
  database: mind_app_test

production:
  <<: *default
  database: mind_app_production
  username: mind_app
  password: <%= ENV['MIND_APP_DATABASE_PASSWORD'] %>
